version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    network_mode: "host"
    command: --bind_ip_all

  backend:
    image: rakesh8289/backend
    container_name: backend
    network_mode: "host"
    environment:
      - PORT=8080

  frontend:
    image: rakesh8289/frontend
    container_name: frontend
    ports:
      - "4200:80"