version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - appnet
    environment:
      - MONGO_INITDB_DATABASE=test

  backend:
    image: rakesh8289/backend
    container_name: backend
    networks:
      - appnet
    environment:
      - MONGO_URL=mongodb://mongodb:27017/test
      - PORT=8080

  frontend:
    image: rakesh8289/frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
