name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug paths
      run: |
        echo "WORKSPACE: $GITHUB_WORKSPACE"
        ls -R .

    - name: Build Backend Image
      working-directory: ${{ github.workspace }}/crud-dd-task-mean-app/backend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend .

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend

    - name: Build Frontend Image
      working-directory: ${{ github.workspace }}/crud-dd-task-mean-app/frontend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend .

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend

    - name: Deploy on EC2
      run: |
        cd /home/ubuntu
        sudo docker-compose down || true
        sudo docker-compose pull
        sudo docker-compose up -d
