name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------
    # 1. CHECKOUT CODE
    # -----------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -----------------------
    # 2. LOGIN TO DOCKER HUB
    # -----------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # -----------------------
    # 3. BUILD BACKEND IMAGE
    # -----------------------
    - name: Build Backend Image
      run: |
        cd ${{ github.workspace }}/crud-dd-task-mean-app/backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend .

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend

    # -----------------------
    # 4. BUILD FRONTEND IMAGE
    # -----------------------
    - name: Build Frontend Image
      run: |
        cd ${{ github.workspace }}/crud-dd-task-mean-app/frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend .

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend

    # -----------------------
    # 5. DEPLOY TO EC2 SERVER
    # -----------------------
    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
