name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted   # your EC2 runner

    steps:

    # ---------------------------------------------------------
    # CHECKOUT CODE
    # ---------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------------------------------------------------------
    # LOGIN TO DOCKER HUB
    # ---------------------------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ---------------------------------------------------------
    # DEBUG WORKSPACE (optional but useful)
    # ---------------------------------------------------------
    - name: Debug workspace
      run: |
        echo "CURRENT DIR: $(pwd)"
        ls -R .

    # ---------------------------------------------------------
    # BUILD BACKEND IMAGE
    # ---------------------------------------------------------
    - name: Build Backend Image
      working-directory: crud-dd-task-mean-app/backend
      run: |
        docker build . \
        --file Dockerfile \
        --tag ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    # ---------------------------------------------------------
    # BUILD FRONTEND IMAGE
    # ---------------------------------------------------------
    - name: Build Frontend Image
      working-directory: crud-dd-task-mean-app/frontend
      run: |
        docker build . \
        --file Dockerfile \
        --tag ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    # ---------------------------------------------------------
    # DEPLOY USING DOCKER COMPOSE (on the EC2 runner
